platform:
  - x64

image:
  - Visual Studio 2017
  - macos

environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn dist

